unbind -a
set -g prefix M-b
unbind C-b
bind M-b send-prefix

unbind -T prefix '"'
unbind -T prefix %

bind d detach-client
bind a send-prefix
bind c new-window
bind n next-window
bind p previous-window
bind & kill-window
bind x kill-pane
bind s choose-session

bind | split-window -h
bind - split-window -v
bind z resize-pane -Z
bind [ copy-mode

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

bind -T prefix 0 select-window -t 0
bind -T prefix 1 select-window -t 1
bind -T prefix 2 select-window -t 2
bind -T prefix 3 select-window -t 3
bind -T prefix 4 select-window -t 4
bind -T prefix 5 select-window -t 5
bind -T prefix 6 select-window -t 6
bind -T prefix 7 select-window -t 7
bind -T prefix 8 select-window -t 8
bind -T prefix 9 select-window -t 9

set -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi


# reload Prefix + r
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"

# peformance
set -g pane-border-style fg="#43445e"
set -g pane-active-border-style fg="#43445e"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-cpu'

# left
set -g status-style bg="#434c5e",fg=white

set -g status-left-length 80
set -g status-right-length 150

set -g status-left '#[fg=#2e3440,bg=#81a1c1,bold]Session:#S#[bg=#434c5e,fg=#81a1c1]'
set -g window-status-separator ""
setw -g window-status-format '#[fg=#d8dee9,bg=#434c5e]#[fg=#2e3440,bg=#d8dee9] #I:#W #[bg=#434c5e,fg=#d8dee9]'
setw -g window-status-current-format '#[fg=#88c0d0,bg=#434c5e]#[fg=#2e3440,bg=#88c0d0,bold] #I:#W #[bg=#434c5e,fg=#88c0d0]'
setw -g window-status-activity-style "fg=#bf616a,bold"

# set -g status-right-length 150
set -g status-right '\
#[fg=#2e3440,bg=#434c5e] #{prefix_highlight} \
#[bg=#434c5e,fg=#d8dee9]#[fg=#2e3440,bg=#d8dee9] RAM #{ram_icon} #{ram_percentage} #[fg=#d8dee9,bg=#434c5e]\
#[bg=#434c5e,fg=#d8dee9]#[fg=#2e3440,bg=#d8dee9] CPU #{cpu_icon} #{cpu_percentage}#[bg=#434c5e,fg=#d8dee9]\
#[fg=#81a1c1,bg=#434c5e]#[fg=#2e3440,bg=#81a1c1] #(date +"%Y-%m-%d %H:%M")'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
