"$schema" = 'https://starship.rs/config-schema.json'
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$aws\
$buf\
$bun\
$c\
$cmake\
$cpp\
$crystal\
$dart\
$deno\
$docker_context\
$elixir\
$elm\
$fennel\
$fossil_branch\
$gcloud\
$golang\
$gradle\
$guix_shell\
$haskell\
$haxe\
$hg_branch\
$java\
$julia\
$kotlin\
$lua\
$memory_usage\
$meson\
$nim\
$nix_shell\
$nodejs\
$ocaml\
$package\
$perl\
$php\
$pijul_channel\
$pixi\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$zig\
$fill\
$conda\
$cmd_duration\
$time\
$line_break\
$character"""

[time]
disabled = false
style = "dimmed white"
format = '[$time]($style) '
time_format = "%R" # HH:MM:SS if HH:MM, set to %R

[directory]
style = "blue"
read_only = " 󰌾"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
style = "purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "purple"
format = "[$all_status$ahead_behind]($style) "

[cmd_duration]
min_time = 2000
style = "yellow"
format = "[$duration]($style) "

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
# symbol = " "
style = "green"
format = '[$symbol$environment]($style) '

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "
style = "blue"
format = '[$symbol$version]($style) '

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "
style = "yellow"
format = '[$symbol$version]($style) '

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
