local M = {}
M.icons = {
    File               = "󰈙 ",
    Module             = " ",
    Namespace          = "󰌗 ",
    Package            = " ",
    Class              = "󰌗 ",
    Method             = "󰆧 ",
    Property           = " ",
    Field              = " ",
    Constructor        = " ",
    Enum               = "󰕘",
    Interface          = "󰕘",
    Function           = "󰊕 ",
    Variable           = "󰆧 ",
    Constant           = "󰏿 ",
    String             = "󰀬 ",
    Number             = "󰎠 ",
    Boolean            = "◩ ",
    Array              = "󰅪 ",
    Object             = "󰅩 ",
    Key                = "󰌋 ",
    Null               = "󰟢 ",
    EnumMember         = " ",
    Struct             = "󰌗 ",
    Event              = " ",
    Operator           = "󰆕 ",
    TypeParameter      = "󰊄 ",
    left_trunc_marker  = "",
    right_trunc_marker = "",
}

M.lsp_icons = {
  array         = { glyph = ' ', hl = 'MiniIconsOrange' },
  boolean       = { glyph = ' ', hl = 'MiniIconsOrange' },
  class         = { glyph = ' ', hl = 'MiniIconsPurple' },
  color         = { glyph = ' ', hl = 'MiniIconsRed'    },
  constant      = { glyph = ' ', hl = 'MiniIconsOrange' },
  constructor   = { glyph = ' ', hl = 'MiniIconsAzure'  },
  enum          = { glyph = ' ', hl = 'MiniIconsPurple' },
  enummember    = { glyph = ' ', hl = 'MiniIconsYellow' },
  event         = { glyph = ' ', hl = 'MiniIconsRed'    },
  field         = { glyph = ' ', hl = 'MiniIconsYellow' },
  file          = { glyph = ' ', hl = 'MiniIconsBlue'   },
  folder        = { glyph = ' ', hl = 'MiniIconsBlue'   },
  Function  = { glyph = '󰊕 ', hl = 'MiniIconsAzure'  },
  interface     = { glyph = ' ', hl = 'MiniIconsPurple' },
  key           = { glyph = ' ', hl = 'MiniIconsYellow' },
  keyword       = { glyph = ' ', hl = 'MiniIconsCyan'   },
  method        = { glyph = ' ', hl = 'MiniIconsAzure'  },
  module        = { glyph = ' ', hl = 'MiniIconsPurple' },
  namespace     = { glyph = ' ', hl = 'MiniIconsRed'    },
  null          = { glyph = ' ', hl = 'MiniIconsGrey'   },
  number        = { glyph = ' ', hl = 'MiniIconsOrange' },
  object        = { glyph = ' ', hl = 'MiniIconsGrey'   },
  operator      = { glyph = ' ', hl = 'MiniIconsCyan'   },
  package       = { glyph = ' ', hl = 'MiniIconsPurple' },
  property      = { glyph = ' ', hl = 'MiniIconsYellow' },
  reference     = { glyph = ' ', hl = 'MiniIconsCyan'   },
  snippet       = { glyph = ' ', hl = 'MiniIconsGreen'  },
  string        = { glyph = ' ', hl = 'MiniIconsGreen'  },
  struct        = { glyph = ' ', hl = 'MiniIconsPurple' },
  text          = { glyph = ' ', hl = 'MiniIconsGreen'  },
  typeparameter = { glyph = ' ', hl = 'MiniIconsCyan'   },
  unit          = { glyph = ' ', hl = 'MiniIconsCyan'   },
  value         = { glyph = ' ', hl = 'MiniIconsBlue'   },
  variable      = { glyph = ' ', hl = 'MiniIconsCyan'   },
}
M.default_icons = {
  default   = { glyph = '󰟢', hl = 'MiniIconsGrey'   },
  directory = { glyph = '󰉋', hl = 'MiniIconsAzure'  },
  extension = { glyph = '󰈔', hl = 'MiniIconsGrey'   },
  file      = { glyph = '󰈔', hl = 'MiniIconsGrey'   },
  filetype  = { glyph = '󰈔', hl = 'MiniIconsGrey'   },
  lsp       = { glyph = '󰞋', hl = 'MiniIconsRed'    },
  os        = { glyph = '󰟀', hl = 'MiniIconsPurple' },
}
return M
